let __id = 0;
const _ = () => __id++;

export const Ids = {
    AIR: _(),
    BEDROCK: _(),
    COAL_ORE: _(),
    COBBLESTONE: _(),
    DIAMOND_ORE: _(),
    DIRT: _(),
    GOLD_ORE: _(),
    GRASS_BLOCK: _(),
    GRASS_BLOCK_SLAB: _(),
    GRASS_BLOCK_STAIRS: _(),
    GRAVEL: _(),
    ICE: _(),
    IRON_ORE: _(),
    PACKED_ICE: _(),
    SAND: _(),
    SNOWY_GRASS_BLOCK: _(),
    STONE: _(),
    TNT: _(),
    WATER: _(),
    LAVA: _(),
    FIRE: _(),
    LOG: _(),
    LEAVES: _(),
    GRASS: _(),
    GRASS_DOUBLE: _(),
    ALLIUM: _(),
    BLUE_ORCHID: _(),
    DANDELION: _(),
    HOUSTONIA: _(),
    ORANGE_TULIP: _(),
    OXEYE_DAISY: _(),
    PAEONIA: _(),
    PINK_TULIP: _(),
    RED_TULIP: _(),
    ROSE: _(),
    WHITE_TULIP: _(),
    NATURAL_LOG: _(),
    SPONGE: _(),
    WET_SPONGE: _(),
    PLANKS: _(),
    CRAFTING_TABLE: _(),
    CHEST: _(),
    FURNACE: _(),
    WOODEN_SLAB: _(),
    STONE_SLAB: _(),
    COBBLESTONE_SLAB: _(),
    DIRT_SLAB: _(),
    WOODEN_STAIRS: _(),
    STONE_STAIRS: _(),
    COBBLESTONE_STAIRS: _(),
    DIRT_STAIRS: _(),
    COAL_BLOCK: _(),
    IRON_BLOCK: _(),
    GOLD_BLOCK: _(),
    DIAMOND_BLOCK: _(),
    ANVIL: _(),
    ENTITY_SPAWNER: _(),

    __MAX_BLOCK: __id - 1,

    APPLE: _(),
    COAL: _(),
    COOKED_BEEF: _(),
    DIAMOND: _(),
    FLINT: _(),
    FLINT_AND_STEEL: _(),
    GOLD_INGOT: _(),
    IRON_INGOT: _(),
    RAW_BEEF: _(),
    WHEAT_SEEDS: _(),
    LEATHER: _(),
    STICK: _(),
    GOLDEN_NUGGET: _(),
    IRON_NUGGET: _(),
    CHARCOAL: _(),
    POTATO: _(),
    BAKED_POTATO: _(),
    RAW_PORKCHOP: _(),
    COOKED_PORKCHOP: _(),
    RAW_MUTTON: _(),
    COOKED_MUTTON: _(),
    RAW_CHICKEN: _(),
    COOKED_CHICKEN: _(),
    SPAWN_EGG: _(),


    WOODEN_SWORD: _(),
    WOODEN_AXE: _(),
    WOODEN_PICKAXE: _(),
    WOODEN_SHOVEL: _(),
    WOODEN_HOE: _(),

    STONE_SWORD: _(),
    STONE_AXE: _(),
    STONE_PICKAXE: _(),
    STONE_SHOVEL: _(),
    STONE_HOE: _(),

    GOLDEN_SWORD: _(),
    GOLDEN_AXE: _(),
    GOLDEN_PICKAXE: _(),
    GOLDEN_SHOVEL: _(),
    GOLDEN_HOE: _(),

    IRON_SWORD: _(),
    IRON_AXE: _(),
    IRON_PICKAXE: _(),
    IRON_SHOVEL: _(),
    IRON_HOE: _(),

    DIAMOND_SWORD: _(),
    DIAMOND_AXE: _(),
    DIAMOND_PICKAXE: _(),
    DIAMOND_SHOVEL: _(),
    DIAMOND_HOE: _(),


    LEATHER_HELMET: _(),
    LEATHER_CHESTPLATE: _(),
    LEATHER_LEGGINGS: _(),
    LEATHER_BOOTS: _(),

    GOLDEN_HELMET: _(),
    GOLDEN_CHESTPLATE: _(),
    GOLDEN_LEGGINGS: _(),
    GOLDEN_BOOTS: _(),

    IRON_HELMET: _(),
    IRON_CHESTPLATE: _(),
    IRON_LEGGINGS: _(),
    IRON_BOOTS: _(),

    DIAMOND_HELMET: _(),
    DIAMOND_CHESTPLATE: _(),
    DIAMOND_LEGGINGS: _(),
    DIAMOND_BOOTS: _(),

    __LEN: _()
};